# What is Numpy

Numpy is a python library that focuses on scientific computing. Numpy has the ability to construct N-dimensional array object, which are similar to list in python. The advantage of Numpy arrays compared to list in python are less memory consumption and faster runtime. Numpy also makes it easer for us to use Linier Algebra, especsially opeartions on vector (1-d array) and matrix (2-d array), Let's Start

## Build Array

In [4]:
# Import Numpy:

import numpy as np

# Example:
# 1
a = np.array([1,2,3])
a

array([1, 2, 3])

In [11]:
# 2
np.zeros(2)

array([0., 0.])

In [21]:
# 3
np.ones(2)

array([1., 1.])

In [13]:
# 4
np.empty(2)

array([1., 1.])

In [15]:
# 5
np.arange(4)

array([0, 1, 2, 3])

In [17]:
# 6
np.linspace(0, 10, num = 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
# Check Tipe:
type(a)

numpy.ndarray

In [19]:
# Check dimensions:
a.ndim

1

In [20]:
# Check array shape:
a.shape

(3,)

## Operation on Array

In [9]:
# Example:
a = np.array([1,2,3])
f = np.array([1.1, 2.2, 3.3])

# sum
a + f

array([2.1, 4.2, 6.3])

In [22]:
# multiple
a*f

array([1.1, 4.4, 9.9])

In [23]:
# quadrat
a**f

array([ 1.        ,  4.59479342, 37.5405076 ])

## Adding and Sorting Elements

In [24]:
# Sort
np.sort([1,4,2,5,2,4])

array([1, 2, 2, 4, 4, 5])

In [25]:
# Concatenate
a = np.sort([1,4,2,4])
b = np.sort([2,1,3,2])
np.concatenate((a,b))

array([1, 2, 4, 4, 1, 2, 2, 3])

## Indexing and Slicing

In [27]:
data = np.array([1,4,3,2])

# Example:
# 1
data[1]

4

In [28]:
# 2
data[0:2]

array([1, 4])

In [29]:
# 3
data[1:]

array([4, 3, 2])

In [34]:
# 4
data[-2]

3

## Indexing and Slicing (with Condition)

In [41]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# Example:
# 1
print(a[a<5])

[1 2 3 4]


In [42]:
# 2
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [43]:
# 3
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [44]:
# 4
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


# vstack() , hstack(), hsplit()

In [46]:
a1 = np.array([[1,1], [2,2]])
a2 = np.array([[3,3], [4,4]])

# 1
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [47]:
# 2
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [49]:
# 3
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [50]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]